# disabled_rules:
#   - statement_position
#   - switch_case_alignment
#   - shorthand_operator
#   - cyclomatic_complexity
#   - file_length
#   - force_cast
#   - function_body_length
#   - function_parameter_count
#   - identifier_name
#   - large_tuple
#   - line_length
#   - type_body_length
#   - type_name

opt_in_rules:
  - number_separator
  - yoda_condition
  - object_literal
  - empty_count
  - private_outlet
  - strict_fileprivate
  - unavailable_function
  - vertical_parameter_alignment_on_call
  - vertical_whitespace
  - yoda_condition
  - force_unwrapping
  
# line_length: 110
# type_body_length:
  # warning: 300
  # error: 400

excluded:
  - Pods/
  - fastlane/
  - Scripts/
  - Templates/
  - Library/Strings.swift
  - bin/strings.swift

reporter: "xcode"

# custom_rules:
#   id_suffix_naming:
#     name: "Wrong name"
#     regex: "(ID)"
#     match_kinds:
#       - identifier
#     message: "Use 'Id' instead 'ID'"
#     severity: error
